### ISSUE TITLE
i can't seem to update my feedsstock any-longer.

### ISSUE THREAD

**Issue by doutriaux1** [conda-forge/feedstocks#13]
PR pass on my fork and on conda-forge to at the end I get:

```
binstar_client.errors.Unauthorized: ('Authorization token is no longer valid', 401)
```

Do I need to merge something in to get the updated token?

**Comment by jakirkham** [comment]
This is a known problem. Please see issue ( https://github.com/conda-forge/conda-forge.github.io/issues/426 ).
