### ISSUE TITLE
submodule for deleted cgsn-parsers-feedstock still present

### ISSUE THREAD

**Issue by mbargull** [conda-forge/feedstocks#21]
I just locally cloned the whole repository but not without issues since Git tried to fetch the `cgsn-parsers-feedstock` which however is deleted/superseded by `cgsn_parsers-feedstock`.

**Comment by jakirkham** [comment]
Thanks @mbargull. There is no step yet to remove feedstocks that have been renamed or deleted. Please see issue ( https://github.com/conda-forge/conda-forge-webservices/issues/152 ) for details. Have manually added PR ( https://github.com/conda-forge/feedstocks/pull/27 ) to remove the feedstock from the `feedstocks` repo.
