### ISSUE TITLE
delete old version?

### ISSUE THREAD

**Issue by scottdraves** [conda-forge/feedstocks#22]
i published some win32 versions of my package (beakerx) by mistake.
these packages would never work.
now we are stuck with an old version that appears confusing:
https://anaconda.org/conda-forge/beakerx

is there any way to delete these (all old win-32 versions).

**Comment by jakirkham** [comment]
Please move this issue to your feedstock and ping core on that issue. Thanks.

**Comment by scottdraves** [comment]
thx i made this: https://github.com/conda-forge/beakerx-feedstock/issues/9
how do i ping core?

**Comment by jakirkham** [comment]
Thanks. Normally `@conda-forge/core` does the trick.
