### ISSUE TITLE
Packaging of linker scripts in -devel packages

### ISSUE THREAD

**Issue by anton-malakhov** [conda-forge/feedstocks#24]
I didn't know where to put this generic existential question concerning many different packages, feedstocks seem like to be related to everyone but please move/suggest accordingly.

I posted a [question on SO](https://stackoverflow.com/q/47355401/2527797), which I'd like to discuss with Conda-Forge maintainers, re-posting it here as well: 

Separating packages into main and -devel parts looks like a good established practice, which allows to save some space for those who are not building software. On Linux, a library that uses SONAME versioning can have two or more files representing a single library, e.g.:

* libABC.so - linker script, e.g. INPUT (libABC.so.1)
* libABC.so.1 - real binary
Where .so file is really used at the build time only, redirecting actual dependency to the versioned file. If so, shouldn't it be placed into libABC-devel.rpm along with include files? It looks inappropriate to put both files to a run-time package, e.g. libABC.rpm.

I also noticed that e.g. Fedora and Conda-forge maintainers replace these linker scripts with symlinks and package them along with the main binary. Is there any reason to do that despite that original library generates linker scripts instead?

**Comment by jakirkham** [comment]
In general, would encourage using basically any other issue tracker than this one. Very few people watch this repo and fewer respond. Just an FYI. More to the point, policy issues (like the one raised here) are best raised on the webpage repo. Admittedly this is probably not at all obvious without knowing this. So we should probably add some sort of doc explaining where these issues should go.

To the issue at hand, this sounds like what was raised in issue ( https://github.com/conda-forge/conda-forge.github.io/issues/157 ). The issue has been a bit quiet and could be revived. A post along these lines seems appropriate there. Though if you have other thoughts about where this should live (new issue vs existing one) please share and we can discuss.

Will close this out as we need to find it a better home where it will garner more attention. Happy to see it over on the webpage repo in some form. Thanks for raising this.
