### ISSUE TITLE
some noarch packages do not work properly

### ISSUE THREAD

**Issue by jochym** [conda-forge/feedstocks#26]
Please some of the maintainers look at the problems with noarch packages causing problems for other packages:
- itsdangerous https://github.com/conda-forge/itsdangerous-feedstock/issues/9
- werkzeug https://github.com/conda-forge/werkzeug-feedstock/issues/8
- nglview https://github.com/conda-forge/nglview-feedstock/issues/5

The affected package is ase (https://github.com/conda-forge/ase-feedstock/pull/15). I had to implement an ugly workaround for this but it would be better if this was fixed upstream. Maybe there should be some guidelines regarding when noarch package should not be used?

**Comment by jakirkham** [comment]
Please migrate this issue to the webpage repo. The feedstocks repo is not a good place to get this kind of support. Thanks.
