### ISSUE TITLE
Doesn't support Python 3.7?

### ISSUE THREAD

**Issue by tats-u** [conda-forge/feedstocks#52]
I tried to install packages in conda-forge to Python 3.7, but they try to downgrading my Python to 3.6.  The auto generated code by @ conda-forge-admin does not support 3.7.

Packages tries to downgrade Python 3.7:
- neovim
  - greenlet
  - msgpack-python
- librosa
  - audioread
- ansible
  - **dogpile.cache**
  - **netifaces**
  - oslo.serialization
  - oslo.utils
  - python-ironicclient
  - shade

**Comment by scopatz** [comment]
@tats-u - please open general issues at https://github.com/conda-forge/conda-forge.github.io Thanks!
