### ISSUE TITLE
Cryptography - ImportError: DLL load failed: The operating system cannot run %1

### ISSUE THREAD

**Issue by Anthon02** [conda-forge/feedstocks#53]
Sorry if I'm in the wrong place. I am trying to create a scrapy project with a version of scrapy installed using  conda install -c conda-forge scrapy .

I am getting the following error. 

> from cryptography.hazmat.bindings._openssl import ffi,lib
> ImportError: DLL load failed: The operating system cannot run %1
> 

I am using phyton 3.6 under miniconda installation on a W7 machine. Any help would be appreciated.

Thanks you

**Comment by scopatz** [comment]
Please open this at https://github.com/conda-forge/cryptography-feedstock
