### ISSUE TITLE
asks did not build properly

### ISSUE THREAD

**Issue by Maxyme** [conda-forge/feedstocks#54]
This feedstock: https://github.com/conda-forge/asks-feedstock did not build properly because of (at the time) missing dependency {"multio[version='>=0.2.3']"} : https://circleci.com/gh/conda-forge/asks-feedstock/1

The multio package is now on conda-forge, so this should rebuild successfully.

**Comment by CJ-Wright** [comment]
I think this has been uploaded now https://circleci.com/gh/conda-forge/asks-feedstock/2
