### ISSUE TITLE
permission error with theano feedstock

### ISSUE THREAD

**Issue by davidslac** [conda-forge/feedstocks#7]
I installed theano from conda-forge, into a centrally installed miniconda. As a user who does not have read/write access, ipython will not load when it tries to read egg files in site packages, I get the error

    OError: [Errno 13] Permission denied: '/central/install/miniconda2/envs/ana/lib/python2.7/site-packages/Theano-0.8.2-py2.7.egg-info/PKG-INFO'

**Comment by jakirkham** [comment]
Thanks for the bug report, @davidslac. As this is pertinent only to the [theano feedstock]( https://github.com/conda-forge/theano-feedstock ), I'm going to move this issue over there.

**Comment by jakirkham** [comment]
Issue moved to [conda-forge/theano-feedstock #2](https://github.com/conda-forge/theano-feedstock/issues/2) via [**ZenHub**](https://www.zenhub.com/)
