### ISSUE TITLE
travis-ci OSX 10.9 image going away soon

### ISSUE THREAD

**Issue by matthew-brett** [conda-forge/feedstocks#8]
Hi - I hope this is the right place to post stuff - but [Tommy Sparber just pointed out](https://bitbucket.org/pygame/pygame/issues/300/os-x-wheels-dmg-and-zip-builds-with-travis) [this announcement](https://blog.travis-ci.com/2016-11-17-retiring-some-osx-images).

Summary - no more OSX 10.9 travis images after Jan 20th.

This may not affect you, but I thought I'd flag it up just in case.  I just emailed support@travis-ci.com to ask for an extension of life for the 10.9 images, maybe consider doing the same if it matters to you?

**Comment by ocefpaf** [comment]
It will affect us and we also wrote them to ask the same. But the answer was not positive. 

Thanks for sharing that! Hopefully the impact won't be too bad.

**Comment by jakirkham** [comment]
Thanks for the ping.

Normally we post this sort of stuff on the webpage issue tracker, but I know that is not obvious.

They were going to drop it on Oct 31st. We begged them for an extension until the New Year. They very generously gave us until Jan 20th. TBH I don't know it is worth asking much more; especially, given 10.9 support can still be gotten from the `xcode6.4` images that will remain after that point. It is more a matter of configuring them correctly. Plus it seems XCode 6.4 fixes a few bugs that XCode 6.1 had.

xref: https://github.com/conda-forge/conda-forge.github.io/issues/249
xref: https://github.com/travis-ci/travis-ci/issues/6765

**Comment by jakirkham** [comment]
As the bulk of the discussion is happening on issue ( https://github.com/conda-forge/conda-forge.github.io/issues/249 ), I'm going to close this to consolidate. Happy to discuss strategy more over there. Thanks again for reaching out.
