### ISSUE TITLE
is it possible to see the CI/appveyor queue?

### ISSUE THREAD

**Issue by jo-tham** [conda-forge/feedstocks#9]
Hi,

first off, big thanks for conda-forge. It's really helped me deliver libraries to my users on multiple platforms.

I did a new release of https://github.com/conda-forge/pygypsy-feedstock yesterday and I notice the appveyor build has been queued for a while. 

I'd like to get an idea of when it will run so I can relay that to people waiting for the build. Is it possible to see the whole queue or get an expected time until the job hits the front?

Thanks!
J

**Comment by ocefpaf** [comment]
All the builds are stuck. I wrote AppVeyor about that and I am still waiting for an answer...

**Comment by jo-tham** [comment]
OK - thanks @ocefpaf

**Comment by jo-tham** [comment]
Seems the builds have resumed. I'll close this since it seemed to be an anomaly
